name: Build AI OS for Poco M3 (citrus)

on:
  workflow_dispatch:

jobs:
  build:
    name: ğŸ”¨ Building ROM
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ§¾ Checkout Source
      uses: actions/checkout@v3

    - name: âš™ï¸ Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl python3 bc bison build-essential zip \
          unzip libncurses5-dev libssl-dev ccache liblz4-tool libxml2 libgl1-mesa-dev \
          libncurses5 curl zlib1g-dev gcc clang repo python-is-python3

    - name: ğŸ—ï¸ Create ROM Folder
      run: |
        mkdir -p rom
        cd rom
        git config --global user.name "Ajay Dash"
        git config --global user.email "ajaydash7978@gmail.com"

    - name: ğŸ“¥ Init Repo
      run: |
        cd rom
        repo init -u https://github.com/PixelOS-AOSP/manifest -b fourteen --depth=1
        git clone https://github.com/Nuapali/AIOS-ROM-Citrus.git .repo/local_manifests

    - name: ğŸ”„ Sync Source
      run: |
        cd rom
        repo sync -c --no-clone-bundle --no-tags --force-sync -j4

    - name: ğŸ› ï¸ Setup Build Environment
      run: |
        cd rom
        source build/envsetup.sh
        lunch aosp_citrus-userdebug

    - name: ğŸ§± Start Build
      run: |
        cd rom
        make bacon -j4

    - name: ğŸ“¤ Upload ROM ZIP
      uses: actions/upload-artifact@v3
      with:
        name: AIOS-ROM-citrus
        path: rom/out/target/product/citrus/*.zip
